OG_MP/OG_MP/urls.py
from django.conf.urls import include, url
from django.conf import settings
urlpatterns = [
    url(r'^', include('mainapp.urls', namespace='mainapp')),
]

OG_MP/mainapp/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [url(r'^$', views.index, name='index'),
               url(r'^visualizer/$', views.data_visualizer, name='data_visualizer')
               ]

OG_MP/mainapp/models.py
from django.db import models

# Create your models here.

OG_MP/mainapp/forms.py
from django import forms


class MineralForm(forms.Form):
    MINERAL_CHOICES = [
        ("PB", "PB"),
        ("CU", "CU"),
        ("ZI", "ZI"),
    ]
    MINERAL_CHOICES = [
        ("PB", "PB"),
        ("CU", "CU"),
        ("ZI", "ZI"),
    ]
    YEAR_CHOICE = [
        ("2012", "2012"),
        ("2013", "2013"),
        ("2014", "2014"),
        ("2015", "2015"),
        ("2016", "2016"),
        ("2017", "2017"),
    ]
    mineral = forms.ChoiceField(
                              choices=MINERAL_CHOICES,
                              widget=forms.Select(attrs={
                                                  'id': 'mineral_input',
                                                  'class': 'form-control'})
                              )
    start_year = forms.ChoiceField(
                                 choices=YEAR_CHOICE,
                                 widget=forms.Select(attrs={
                                                     'id': 'start_year',
                                                     'class': 'form-control'})
                                 )
    end_year = forms.ChoiceField(
                               choices=YEAR_CHOICE,
                               widget=forms.Select(attrs={
                                                   'id': 'end_year',
                                                   'class': 'form-control'}))
    def clean(self):
        cleaned_data = super(MineralForm, self).clean()
        mineral = cleaned_data.get("mineral")
        start_year = cleaned_data.get("start_year")
        end_year = cleaned_data.get("end_year")

        if int(start_year) > int(end_year):
            msg = "End Year should be greater than or equal to Start Year"
            self.add_error('end_year', msg)

OG_MP/mainapp/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
import json
import quandl
from . import forms
from django.http import HttpResponse, JsonResponse, Http404
from bokeh.plotting import figure
from bokeh.resources import CDN
from bokeh.embed import components
from bokeh.models import HoverTool, Range1d

quandl.ApiConfig.api_key = 'hEK_VDFz71bd88AKikmB'


def index(request):
    form = forms.MineralForm(initial={'end_year': '2017'})
    return render(request, 'mainapp/index.html', {"form": form})


def data_visualizer(request):
    form = forms.MineralForm(request.GET)
    if form.is_valid():
        start_year = form.cleaned_data['start_year']
        end_year = form.cleaned_data['end_year']
        mineral = form.cleaned_data['mineral']
        values = quandl.get("LME/PR_{mineral}".format(mineral=mineral), start_date="{year}-01-01".format(year=start_year), end_date="{year}-12-31".format(year=end_year))
        avg = values["Cash Buyer"].mean()
        values["mean"] = avg
        m = values["mean"].values
        x = values["Cash Buyer"].keys()
        y = values["Cash Buyer"].values
        plot = figure(title="Stock Price for {mineral} {start}/01/01-{end}/12/31".format(mineral=mineral, start=start_year, end=end_year),
                      x_axis_label='date',
                      y_axis_label='price',
                      plot_width =800,
                      plot_height =400,
                      responsive=True,
                      x_axis_type="datetime",
                      toolbar_location="right",
                     )
        plot.y_range = Range1d(1500, 3000)
        price_line = plot.line(x, y, color='#ff8c43', line_width=1, line_alpha=0.5, legend='price')
        hover = HoverTool(tooltips=[
            ("date", "@x{%F}"),
            ("price", "@y")
        ],
        renderers=[price_line],  # show tooltip for only one line
        formatters={
            'x'      : 'datetime', # use 'datetime' formatter for 'date' field
            'y' : 'printf',   # use 'printf' formatter for 'adj close' field
        },
        mode='vline')
        hover.formatters = {"x": "datetime"}  # trasnform value of x to date
        plot.line(x, m, color='black',line_width=2, line_alpha=0.2, legend='mean', line_dash="4 4")  # mean line
        plot.add_tools(hover)
        script, graph = components(plot, CDN)
        return render(request, 'mainapp/index.html', {"form": form, "script": script, "graph": graph, "avg": avg})
    else:
        return render(request, 'mainapp/index.html', {"form": form})

OG_MP/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="{% block language %}{% endblock %}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!--Css styles-->
    <link href="{% static 'mainstyles/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="{% static 'mainstyles/font-awesome.min.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
    <!--END Css styles-->
</head>

<body class="clearfix d-flex align-items-start flex-column">
  <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-dark bg-dark w-100" id="site-navbar">
    <a class="navbar-brand" href="{% url 'mainapp:index' %}">Metal Average Price</a>
    <div id="navbar" class="navbar-collapse collapse" style="width:auto">
      <ul class="nav navbar-nav ml-auto">
          <li class="nav-item"><a class="nav-link" target="_blank" href="http://opengeostat.com/">OpenGeostat</a></li>
      </ul>
    </div>
    </nav>
    <div class="container-fluid">
        {% block body_content %} {% endblock %}
    </div>
    {% include "mainapp/footer.html" %}
</body>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
</html>

OG_MP/mainapp/templates/mainapp/footer.html
{% load static %}
<footer class="mt-auto w-100 bg-light pt-3" id="site-footer">
  <div class="text-center">
    <a class="text-dark" target="_blank" href="http://opengeostat.com/">
      <img src="{% static "opengeostat.png" %}"/> <br />
      Created by OpenGeostat
    </a>
  </div>
  <div class="text-center">
  </div>
  <p class="text-light text-center mt-3 py-3 bg-info mb-auto">Source: <a class="text-light" href="https://www.quandl.com/data/LME-London-Metal-Exchange" target="_blank">London Metal Exchange</a></p>
</footer>

OG_MP/mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block language %}en{% endblock %}
{% block title %}Metal Average Price{% endblock %}
{% block css %}
    <link rel="stylesheet" href="https://cdn.pydata.org/bokeh/release/bokeh-0.12.10.min.css" type="text/css" />
{% endblock %}
{% block body_content %}
<div class="row">
<div class="{% if graph %}col-lg-5{% else %}col-md-6 mx-auto{% endif %}">
    <form method="GET" action="{% url "mainapp:data_visualizer" %}" class="form-row mt-2">
      <div class="form-group col-12">
        <label for="exampleInputEmail1">Mineral</label>
        {{ form.mineral }}
      </div>
      {% if form.end_year.errors %}
      <div class="alert alert-danger alert-dismissible fade show pb-0 px-2 col-12" role="alert">
        <strong>{{ form.end_year.errors.as_text }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %}
      <div class="form-group col-6">
        <label for="exampleInputEmail1">Start Year</label>
        {{ form.start_year }}
      </div>
      <div class="form-group col-6">
        <label for="exampleInputEmail1">End Year</label>
        {{ form.end_year }}
      </div>
      <button type="submit" name="submit" class="btn btn-dark ml-auto mr-1">Plot</button>
    </form>
</div>
{% if graph %}
<div class="col-lg-6 col-11 mx-auto">
  <h4 class="mt-2">Average: {{ avg }}</h4>
  <div class="graph-container">
  <div id="graph">
    {{ graph|safe }}
  </div>
  </div>
</div>
{% endif %}
</div>
<style>
html{
    height: 100%;
    }
body{
    min-height: 100%
}
.btn {
  cursor: pointer
}
</style>
{% endblock %}
{% block script %}
<script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.10.min.js"></script>
<script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-api-0.12.10.min.js"></script>
{{ script|safe }}
{% endblock %}